server:
  port: 8090

spring:
  application:
    name: employeeservice
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:userdb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQl_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
#  security:
#    user:
#      name: user
#      password: password